"""First Migration

Revision ID: 2484afc03912
Revises: 
Create Date: 2024-05-08 09:25:45.871643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2484afc03912'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Station_id'), 'Station', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_bio'), 'User', ['bio'], unique=False)
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=False)
    op.create_table('Address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('box_number', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Address_area'), 'Address', ['area'], unique=False)
    op.create_index(op.f('ix_Address_box_number'), 'Address', ['box_number'], unique=False)
    op.create_index(op.f('ix_Address_description'), 'Address', ['description'], unique=False)
    op.create_index(op.f('ix_Address_district'), 'Address', ['district'], unique=False)
    op.create_index(op.f('ix_Address_id'), 'Address', ['id'], unique=False)
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['Station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Admin_position'), 'Admin', ['position'], unique=False)
    op.create_table('Parcel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['Station.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['Station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Parcel_description'), 'Parcel', ['description'], unique=False)
    op.create_index(op.f('ix_Parcel_id'), 'Parcel', ['id'], unique=False)
    op.create_index(op.f('ix_Parcel_name'), 'Parcel', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Parcel_name'), table_name='Parcel')
    op.drop_index(op.f('ix_Parcel_id'), table_name='Parcel')
    op.drop_index(op.f('ix_Parcel_description'), table_name='Parcel')
    op.drop_table('Parcel')
    op.drop_index(op.f('ix_Admin_position'), table_name='Admin')
    op.drop_table('Admin')
    op.drop_index(op.f('ix_Address_id'), table_name='Address')
    op.drop_index(op.f('ix_Address_district'), table_name='Address')
    op.drop_index(op.f('ix_Address_description'), table_name='Address')
    op.drop_index(op.f('ix_Address_box_number'), table_name='Address')
    op.drop_index(op.f('ix_Address_area'), table_name='Address')
    op.drop_table('Address')
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_index(op.f('ix_User_bio'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Station_id'), table_name='Station')
    op.drop_table('Station')
    # ### end Alembic commands ###
